# Setup
title: Nathan's notes

# Handling Reading
include:      [".htaccess"]
exclude:      [vendor]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,md"

# Plugins
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-pagination

# Serving
detach:  false
port:    4000
host:    127.0.0.1

# Outputting
permalink:     /n/:year/:month/:day/:slug/
paginate_path: /:num
paginate: 25
