# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:           Nathan's Notes 
tagline:          'Developer interested in the open source community'
description:      'Blog full of quick tech notes and rambles/thoughts on unrelated topics.'
url:               nathanisom27.github.io

author:
  name:           'Nathan Isom'
  url:            nathanisom27.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:           https://github.com/nathanisom27
#  repo:           
