# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:       /posts/:month-:day-:year/:title.html 

# Setup
title:           Nathan's Notes 

author:
  name:           'Nathan Isom'
  url:            https://neeasa.de
Pager:            paginate
paginate:         10

collections:
- blog
# Custom vars
version:          2.0.0

prose:
  siteurl:"http://neeasa.de"
  media:"media"
  
  
